name: Docker ARM64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-22.04-arm64 # 指定为支持ARM64的Ubuntu 22.04运行器

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build. --file Dockerfile --tag my-image-name:$(date +%s)
